config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  resources :tweets, only: [:index, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tests = Tweet.all
    if @tests.present?
      @test = Tweet.last
      binding.pry
      if @test.year_record == Time.now.year && @test.month_record == Time.now.month && @test.day_record == Time.now.day
        @time = @test
        if params[:id].present?
          @test = Tweet.find(params[:id]).last
        end
      end
      @test = Tweet.new
    end
  end

  def create
    @test = Tweet.new(timerecord_params)
    @test.save
    redirect_to root_path
  end
  def update
    @test = Tweet.new(timerecord_params)
    @test.update
    redirect_to root_path
  end

  private
  def timerecord_params
    params.permit(:time_record, :year_record, :month_record, :day_record)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordTest1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<% if @time.present? %>
  <%= form_with module:@test, url: tweet_path(id:@test.id) do |f| %>
    <%= f.text_field :year_record,value:Time.now.year %>
    <%= f.text_field :month_record,value:Time.now.month %>
    <%= f.text_field :day_record,value:Time.now.day %>
    <%= f.text_field :time_record,value:@time.time_record+1 %>
    <%= f.submit "保存"  %>
  <% end %>
<% else %>
  <%= form_with module:@test, url: tweets_path do |f| %>
    <%= f.text_field :year_record,value:Time.now.year %>
    <%= f.text_field :month_record,value:Time.now.month %>
    <%= f.text_field :day_record,value:Time.now.day %>
    <%= f.text_field :time_record,value:1 %>
    <%= f.submit "保存"  %>
  <% end %>
<% end %>